import{firebaseConfig}from"./firebase-config.js";
import{studyConfig}from"./study-config.js";

const $=s=>document.querySelector(s),screens=["intro","instructions","annotate","complete","declined"];
const labels={revision_relation_label:[["replace","Replaced","The new rule completely takes the old rule's place"],["narrow","More restrictive","The new rule allows less than before"],["expand","Broader","The new rule allows more than before"],["exception","Added an exception","The old rule remains, with a new special case"],["cancel","Cancelled","The old rule is withdrawn"],["reschedule","Changed the timing","The task stays, but its time changes"],["clarify","Clarified only","Wording becomes clearer; meaning stays the same"],["unclear","Cannot tell","There is not enough information"]],action_consistency_label:[["current","Follows the new rule","The proposed action matches the current instruction"],["legacy","Follows the old rule","It follows the earlier instruction instead"],["mixed","Mixes old and new","It combines requirements from both versions"],["abstention","Waits or checks","It does not act yet, or asks for verification"],["unclear","Cannot tell","There is not enough information"]],write_consistency_label:[["current","Saves the new rule","A future agent would learn the current instruction"],["legacy","Saves the old rule","A future agent would learn the earlier instruction"],["mixed","Saves a mixture","It combines old and new instructions"],["empty","Saves nothing","No lasting instruction is recorded"],["unclear","Cannot tell","It is unclear what a future agent would learn"]],mixed_validity_preservation_label:[["preserved","Kept correctly","The part that did not change is retained"],["corrupted_or_omitted","Changed or missing","A still-valid part is damaged or left out"],["not_applicable","No unchanged part","Nothing from the old rule needed to remain"],["unclear","Cannot tell","There is not enough information"]]};
const state={participantKey:null,studyKey:null,sessionKey:null,batchId:null,batches:{},items:[],tasks:new Map(),index:0,answers:{},uid:null,db:null,firebase:null,prolific:null,preview:false};
function show(id){screens.forEach(x=>$("#"+x).classList.toggle("active",x===id));scrollTo({top:0,behavior:"smooth"})}
function configured(v){return typeof v==="string"&&v.length>0&&!v.startsWith("CONFIGURE_")}
function ethicsReady(){const e=studyConfig.ethics,p=studyConfig.prolific,s=studyConfig.study;return e.status==="APPROVED"&&[e.institution,e.reference,e.approvedDate,e.contactName,e.contactEmail,s.estimatedMinutes,s.payment,p.completionCode].every(configured)}
function renderStudyInfo(){const e=studyConfig.ethics,reviewConfigured=e.status==="APPROVED"&&[e.institution,e.reference,e.approvedDate,e.contactName,e.contactEmail].every(configured);$("#ethicsCard").hidden=!reviewConfigured;if(reviewConfigured){$("#ethicsStatus").textContent="Reviewed and approved";$("#ethicsInstitution").textContent=e.institution;$("#ethicsReference").textContent=e.reference;$("#ethicsDate").textContent=e.approvedDate;$("#ethicsContact").textContent=`${e.contactName} · ${e.contactEmail}`;$("#ethicsNotice").textContent=`${studyConfig.study.risks} ${studyConfig.study.withdrawal}`}$("#durationText").textContent=configured(studyConfig.study.estimatedMinutes)?`Estimated duration: ${studyConfig.study.estimatedMinutes} minutes.`:"Estimated duration and payment are shown in the Prolific study listing.";$("#paymentText").textContent=configured(studyConfig.study.payment)?`Payment: ${studyConfig.study.payment}.`:"Payment: see the Prolific study listing."}
function prolificParams(){const q=new URLSearchParams(location.search),get=k=>q.get(k)||q.get(k.toLowerCase());return{pid:get("PROLIFIC_PID"),studyId:get("STUDY_ID"),sessionId:get("SESSION_ID"),preview:q.get("preview")==="1"}}
async function hash(v){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function storageKey(){return`vmts_prolific_${state.participantKey}`}
function optionHTML(name,values){return values.map(([v,l,h])=>`<label class="option"><input type="radio" name="${name}" value="${v}"><span><b>${l}</b>${h?`<small>${h}</small>`:""}</span></label>`).join("")}
function initOptions(){$("#revisionOptions").innerHTML=optionHTML("revision_relation_label",labels.revision_relation_label);$("#actionOptions").innerHTML=optionHTML("action_consistency_label",labels.action_consistency_label);$("#writeOptions").innerHTML=optionHTML("write_consistency_label",labels.write_consistency_label);$("#preservationOptions").innerHTML=optionHTML("mixed_validity_preservation_label",labels.mixed_validity_preservation_label);$("#confidenceOptions").innerHTML=optionHTML("confidence_1_to_5",[["1","1"],["2","2"],["3","3"],["4","4"],["5","5"]])}
async function loadData(){const[t,b]=await Promise.all([fetch("data/tasks.json").then(r=>r.json()),fetch("data/prolific-batches.json").then(r=>r.json())]);state.tasks=new Map(t.map(x=>[x.item_id,x]));state.batches=b}
async function connectFirebase(){if(!firebaseConfig.apiKey)throw new Error("Firebase is not configured.");const[{initializeApp},{getAuth,signInAnonymously},{getFirestore,doc,setDoc,serverTimestamp,runTransaction}]=await Promise.all([import("https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js"),import("https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js"),import("https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js")]);const app=initializeApp(firebaseConfig),cred=await signInAnonymously(getAuth(app));state.uid=cred.user.uid;state.db=getFirestore(app);state.firebase={doc,setDoc,serverTimestamp,runTransaction};$("#saveState").textContent="Securely connected"}
async function assignBatch(){const{doc,runTransaction,serverTimestamp}=state.firebase,participantRef=doc(state.db,"participants",state.participantKey),ids=Object.keys(state.batches).sort(),offset=parseInt(state.participantKey.slice(0,8),16)%ids.length,ordered=ids.slice(offset).concat(ids.slice(0,offset));state.batchId=await runTransaction(state.db,async tx=>{const existing=await tx.get(participantRef);if(existing.exists()){const d=existing.data();if(d.uid!==state.uid)throw new Error("This Prolific ID was already started in another browser profile. Contact the researcher.");return d.batchId}const claims=[];for(const id of ordered)claims.push([id,await tx.get(doc(state.db,"batchClaims",id))]);const available=claims.find(([,snap])=>!snap.exists());if(!available)throw new Error("All annotation places are currently assigned. Return the study on Prolific or contact the researcher.");const batchId=available[0],common={participantKey:state.participantKey,batchId,uid:state.uid,studyKey:state.studyKey,sessionKey:state.sessionKey,assignedAt:serverTimestamp()};tx.set(doc(state.db,"batchClaims",batchId),common);tx.set(participantRef,common);return batchId});if(!state.batches[state.batchId])throw new Error("Assigned batch is missing from this site version.");state.items=state.batches[state.batchId]}
function assignPreviewBatch(){const ids=Object.keys(state.batches).sort(),offset=parseInt(state.participantKey.slice(0,8),16)%ids.length;state.batchId=`PREVIEW-${ids[offset]}`;state.items=state.batches[ids[offset]]}
function restore(){try{state.answers=JSON.parse(localStorage.getItem(storageKey())||"{}")}catch{state.answers={}}const first=state.items.findIndex(id=>!state.answers[id]?.submitted);state.index=first<0?state.items.length:first}
function render(){if(state.index>=state.items.length)return finish();const id=state.items[state.index],t=state.tasks.get(id),a=state.answers[id]||{};$("#counter").textContent=`Item ${state.index+1} of ${state.items.length}`;$("#sessionHint").textContent=state.index===9?"Suggested short break":"";$("#progressBar").style.width=`${100*state.index/state.items.length}%`;const fields=[["oldAction","old_action","Earlier instruction"],["currentAction","current_action","Current instruction"],["preserved","preserved_clause","Still-valid clause"],["invalidated","invalidated_clause","Invalidated clause"],["newClause","new_clause","New clause"],["candidateAction","candidate_action","Candidate action"],["candidateWrite","candidate_write","Candidate saved write"]],truncated=new Set(t.truncated_fields||[]);fields.forEach(([el,k])=>{const node=$("#"+el);node.textContent=t[k]||"(empty)";node.classList.toggle("is-truncated",truncated.has(k))});const names=fields.filter(([,k])=>truncated.has(k)).map(([, ,name])=>name),warning=$("#truncationWarning");warning.hidden=!names.length;warning.textContent=names.length?`Source-data warning: ${names.join(", ")} may be truncated. Treat visible text as incomplete.`:"";$("#annotationForm").reset();Object.entries(a).forEach(([k,v])=>{const x=document.querySelector(`[name="${k}"][value="${CSS.escape(String(v))}"]`);if(x)x.checked=true});$("#notes").value=a.notes||"";$("#formError").textContent=""}
function collect(){const fd=new FormData($("#annotationForm")),o={};for(const k of Object.keys(labels))o[k]=fd.get(k);o.confidence_1_to_5=fd.get("confidence_1_to_5");o.notes=$("#notes").value.trim();return o}
async function saveCurrent(){const itemId=state.items[state.index],answer=collect(),missing=[...Object.keys(labels),"confidence_1_to_5"].filter(k=>!answer[k]);if(missing.length){$("#formError").textContent="Please answer all five required questions.";return false}const payload={...answer,itemId,batchId:state.batchId,participantKey:state.participantKey,studyKey:state.studyKey,sessionKey:state.sessionKey,uid:state.uid,submitted:true,clientUpdatedAt:new Date().toISOString()};state.answers[itemId]=payload;localStorage.setItem(storageKey(),JSON.stringify(state.answers));if(state.preview){$("#saveState").textContent="Preview only — saved in this browser";return true}try{const{doc,setDoc,serverTimestamp}=state.firebase;await setDoc(doc(state.db,"responses",`${state.participantKey}_${itemId}`),{...payload,serverUpdatedAt:serverTimestamp()},{merge:true});$("#saveState").textContent="Saved securely"}catch(e){console.error(e);$("#formError").textContent="Could not save to the study database. Check your connection and try again.";$("#saveState").textContent="Save failed";return false}return true}
async function finish(){show("complete");if(state.preview){$("#completionCode").textContent="PREVIEW ONLY";$("#completeText").textContent=`Preview complete. ${state.items.length} test responses stayed in this browser and were not submitted.`;$("#prolificReturnBtn").hidden=true;return}$("#completionCode").textContent=studyConfig.prolific.completionCode;$("#completeText").textContent=`All ${state.items.length} responses have been saved. Return to Prolific to record your submission.`;$("#prolificReturnBtn").href=studyConfig.prolific.completionUrl;try{const{doc,setDoc,serverTimestamp}=state.firebase;await setDoc(doc(state.db,"participants",state.participantKey),{completedAt:serverTimestamp(),completedItems:Object.keys(state.answers).length},{merge:true})}catch(e){console.error(e)}}
function download(){const blob=new Blob([JSON.stringify({batchId:state.batchId,participantKey:state.participantKey,responses:Object.values(state.answers)},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="vmts-participant-backup.json";a.click();URL.revokeObjectURL(a.href)}

renderStudyInfo();initOptions();state.prolific=prolificParams();state.preview=state.prolific.preview;$("#participantStatus").textContent=state.preview?"Preview mode — no data will be submitted and no study slot will be claimed.":state.prolific.pid&&state.prolific.studyId&&state.prolific.sessionId?"Prolific study link detected. Your task set will be assigned after consent.":"This URL is missing Prolific participant parameters. Open the study from Prolific.";if(state.preview)$("#saveState").textContent="PREVIEW — no data submission";
$("#beginBtn").onclick=async()=>{const error=$("#introError");error.textContent="";const p=state.prolific;if(state.preview){$("#beginBtn").disabled=true;try{const previewId=p.pid||"LOCAL-PREVIEW";[state.participantKey,state.studyKey,state.sessionKey]=await Promise.all([hash(`preview|${previewId}`),hash("preview-study"),hash("preview-session")]);await loadData();assignPreviewBatch();restore();show("instructions")}catch(e){console.error(e);error.textContent="Preview could not be started.";$("#beginBtn").disabled=false}return}if(!ethicsReady())return error.textContent="This study is not yet open. Please return the submission on Prolific or contact the researcher.";if(!p.pid||!p.studyId||!p.sessionId)return error.textContent="The Prolific participant, study, or session parameter is missing. Re-open the task from Prolific.";if(studyConfig.prolific.expectedStudyId&&p.studyId!==studyConfig.prolific.expectedStudyId)return error.textContent="This link belongs to a different Prolific study.";$("#beginBtn").disabled=true;$("#participantStatus").textContent="Assigning your task set…";try{[state.participantKey,state.studyKey,state.sessionKey]=await Promise.all([hash(`vmts|${p.studyId}|${p.pid}`),hash(p.studyId),hash(p.sessionId)]);await loadData();await connectFirebase();await assignBatch();restore();show("instructions")}catch(e){console.error(e);error.textContent=e.message||"The study could not be started. Contact the researcher.";$("#beginBtn").disabled=false}};
$("#declineBtn").onclick=()=>{state.answers={};show("declined");if(state.preview)return;const url=studyConfig.prolific.declineUrl||"https://app.prolific.com/";$("#declineReturnBtn").href=url;setTimeout(()=>location.assign(url),1500)};
$("#startBtn").onclick=()=>{if(state.index>=state.items.length)return finish();show("annotate");render()};$("#annotationForm").onsubmit=async e=>{e.preventDefault();if(await saveCurrent()){state.index++;render()}};$("#backBtn").onclick=()=>{if(state.index>0){state.index--;render()}};$("#exportBtn").onclick=download;$("#clearBtn").onclick=()=>{$("#annotationForm").reset();$("#notes").value="";$("#formError").textContent=""};
