import{firebaseConfig}from"./firebase-config.js";
import{studyConfig}from"./study-config.js";

const $=s=>document.querySelector(s),screens=["intro","instructions","annotate","complete"];
const labels={revision_relation_label:[["replace","Replace","Earlier instruction is fully superseded"],["narrow","Narrow","Current instruction reduces the allowed scope"],["expand","Expand","Current instruction adds allowed scope"],["exception","Exception","Current instruction adds a special-case override"],["cancel","Cancel","Earlier instruction is withdrawn"],["reschedule","Reschedule","Timing changes while the task remains"],["clarify","Clarify","Meaning is clearer without a substantive change"],["unclear","Unclear","The relation cannot be determined"]],action_consistency_label:[["current","Current","Follows the current instruction"],["legacy","Legacy","Follows the earlier instruction instead"],["mixed","Mixed","Combines current and legacy requirements"],["abstention","Abstention","Explicitly defers, verifies, or does not act"],["unclear","Unclear","Cannot determine from the text"]],write_consistency_label:[["current","Current","Future agent inherits the current rule"],["legacy","Legacy","Future agent inherits the earlier rule"],["mixed","Mixed","Combines current and legacy rules"],["empty","Empty","No persistent instruction is saved"],["unclear","Unclear","Cannot determine what is inherited"]],mixed_validity_preservation_label:[["preserved","Preserved","Still-valid clause is retained correctly"],["corrupted_or_omitted","Corrupted / omitted","Still-valid clause is changed or missing"],["not_applicable","Not applicable","No still-valid clause is relevant"],["unclear","Unclear","Preservation cannot be determined"]]};
const state={participantKey:null,studyKey:null,sessionKey:null,batchId:null,batches:{},items:[],tasks:new Map(),index:0,answers:{},uid:null,db:null,firebase:null,prolific:null};
function show(id){screens.forEach(x=>$("#"+x).classList.toggle("active",x===id));scrollTo({top:0,behavior:"smooth"})}
function configured(v){return typeof v==="string"&&v.length>0&&!v.startsWith("CONFIGURE_")}
function ethicsReady(){const e=studyConfig.ethics,p=studyConfig.prolific,s=studyConfig.study;return e.status==="APPROVED"&&[e.institution,e.reference,e.approvedDate,e.contactName,e.contactEmail,s.estimatedMinutes,s.payment,p.completionCode].every(configured)}
function renderStudyInfo(){const e=studyConfig.ethics,ready=ethicsReady();$("#ethicsStatus").textContent=ready?"Approved":"Recruitment locked — approval details required";$("#ethicsInstitution").textContent=configured(e.institution)?e.institution:"Not configured";$("#ethicsReference").textContent=configured(e.reference)?e.reference:"Not configured";$("#ethicsDate").textContent=configured(e.approvedDate)?e.approvedDate:"Not configured";$("#ethicsContact").textContent=configured(e.contactName)&&configured(e.contactEmail)?`${e.contactName} · ${e.contactEmail}`:"Not configured";$("#ethicsNotice").textContent=ready?`${studyConfig.study.risks} ${studyConfig.study.withdrawal}`:"Enter the genuine approval and study details in study-config.js. Participants cannot begin until this is complete.";$("#ethicsCard").classList.toggle("not-ready",!ready);$("#durationText").textContent=`Estimated duration: ${configured(studyConfig.study.estimatedMinutes)?studyConfig.study.estimatedMinutes+" minutes":"not configured"}.`;$("#paymentText").textContent=`Payment: ${configured(studyConfig.study.payment)?studyConfig.study.payment:"not configured"}.`}
function prolificParams(){const q=new URLSearchParams(location.search),get=k=>q.get(k)||q.get(k.toLowerCase());return{pid:get("PROLIFIC_PID"),studyId:get("STUDY_ID"),sessionId:get("SESSION_ID")}}
async function hash(v){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function storageKey(){return`vmts_prolific_${state.participantKey}`}
function optionHTML(name,values){return values.map(([v,l,h])=>`<label class="option"><input type="radio" name="${name}" value="${v}"><span><b>${l}</b>${h?`<small>${h}</small>`:""}</span></label>`).join("")}
function initOptions(){$("#revisionOptions").innerHTML=optionHTML("revision_relation_label",labels.revision_relation_label);$("#actionOptions").innerHTML=optionHTML("action_consistency_label",labels.action_consistency_label);$("#writeOptions").innerHTML=optionHTML("write_consistency_label",labels.write_consistency_label);$("#preservationOptions").innerHTML=optionHTML("mixed_validity_preservation_label",labels.mixed_validity_preservation_label);$("#confidenceOptions").innerHTML=optionHTML("confidence_1_to_5",[["1","1"],["2","2"],["3","3"],["4","4"],["5","5"]])}
async function loadData(){const[t,b]=await Promise.all([fetch("data/tasks.json").then(r=>r.json()),fetch("data/prolific-batches.json").then(r=>r.json())]);state.tasks=new Map(t.map(x=>[x.item_id,x]));state.batches=b}
async function connectFirebase(){if(!firebaseConfig.apiKey)throw new Error("Firebase is not configured.");const[{initializeApp},{getAuth,signInAnonymously},{getFirestore,doc,setDoc,serverTimestamp,runTransaction}]=await Promise.all([import("https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js"),import("https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js"),import("https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js")]);const app=initializeApp(firebaseConfig),cred=await signInAnonymously(getAuth(app));state.uid=cred.user.uid;state.db=getFirestore(app);state.firebase={doc,setDoc,serverTimestamp,runTransaction};$("#saveState").textContent="Securely connected"}
async function assignBatch(){const{doc,runTransaction,serverTimestamp}=state.firebase,participantRef=doc(state.db,"participants",state.participantKey),ids=Object.keys(state.batches).sort(),offset=parseInt(state.participantKey.slice(0,8),16)%ids.length,ordered=ids.slice(offset).concat(ids.slice(0,offset));state.batchId=await runTransaction(state.db,async tx=>{const existing=await tx.get(participantRef);if(existing.exists()){const d=existing.data();if(d.uid!==state.uid)throw new Error("This Prolific ID was already started in another browser profile. Contact the researcher.");return d.batchId}const claims=[];for(const id of ordered)claims.push([id,await tx.get(doc(state.db,"batchClaims",id))]);const available=claims.find(([,snap])=>!snap.exists());if(!available)throw new Error("All annotation places are currently assigned. Return the study on Prolific or contact the researcher.");const batchId=available[0],common={participantKey:state.participantKey,batchId,uid:state.uid,studyKey:state.studyKey,sessionKey:state.sessionKey,assignedAt:serverTimestamp()};tx.set(doc(state.db,"batchClaims",batchId),common);tx.set(participantRef,common);return batchId});if(!state.batches[state.batchId])throw new Error("Assigned batch is missing from this site version.");state.items=state.batches[state.batchId]}
function restore(){try{state.answers=JSON.parse(localStorage.getItem(storageKey())||"{}")}catch{state.answers={}}const first=state.items.findIndex(id=>!state.answers[id]?.submitted);state.index=first<0?state.items.length:first}
function render(){if(state.index>=state.items.length)return finish();const id=state.items[state.index],t=state.tasks.get(id),a=state.answers[id]||{};$("#counter").textContent=`Item ${state.index+1} of ${state.items.length}`;$("#sessionHint").textContent=state.index===9?"Suggested short break":"";$("#progressBar").style.width=`${100*state.index/state.items.length}%`;const fields=[["oldAction","old_action","Earlier instruction"],["currentAction","current_action","Current instruction"],["preserved","preserved_clause","Still-valid clause"],["invalidated","invalidated_clause","Invalidated clause"],["newClause","new_clause","New clause"],["candidateAction","candidate_action","Candidate action"],["candidateWrite","candidate_write","Candidate saved write"]],truncated=new Set(t.truncated_fields||[]);fields.forEach(([el,k])=>{const node=$("#"+el);node.textContent=t[k]||"(empty)";node.classList.toggle("is-truncated",truncated.has(k))});const names=fields.filter(([,k])=>truncated.has(k)).map(([, ,name])=>name),warning=$("#truncationWarning");warning.hidden=!names.length;warning.textContent=names.length?`Source-data warning: ${names.join(", ")} may be truncated. Treat visible text as incomplete.`:"";$("#annotationForm").reset();Object.entries(a).forEach(([k,v])=>{const x=document.querySelector(`[name="${k}"][value="${CSS.escape(String(v))}"]`);if(x)x.checked=true});$("#notes").value=a.notes||"";$("#formError").textContent=""}
function collect(){const fd=new FormData($("#annotationForm")),o={};for(const k of Object.keys(labels))o[k]=fd.get(k);o.confidence_1_to_5=fd.get("confidence_1_to_5");o.notes=$("#notes").value.trim();return o}
async function saveCurrent(){const itemId=state.items[state.index],answer=collect(),missing=[...Object.keys(labels),"confidence_1_to_5"].filter(k=>!answer[k]);if(missing.length){$("#formError").textContent="Please answer all five required questions.";return false}const payload={...answer,itemId,batchId:state.batchId,participantKey:state.participantKey,studyKey:state.studyKey,sessionKey:state.sessionKey,uid:state.uid,submitted:true,clientUpdatedAt:new Date().toISOString()};state.answers[itemId]=payload;localStorage.setItem(storageKey(),JSON.stringify(state.answers));try{const{doc,setDoc,serverTimestamp}=state.firebase;await setDoc(doc(state.db,"responses",`${state.participantKey}_${itemId}`),{...payload,serverUpdatedAt:serverTimestamp()},{merge:true});$("#saveState").textContent="Saved securely"}catch(e){console.error(e);$("#formError").textContent="Could not save to the study database. Check your connection and try again.";$("#saveState").textContent="Save failed";return false}return true}
async function finish(){show("complete");$("#completionCode").textContent=studyConfig.prolific.completionCode;$("#completeText").textContent=`All ${state.items.length} responses have been saved. Return to Prolific to record your submission.`;$("#prolificReturnBtn").href=studyConfig.prolific.completionUrl;try{const{doc,setDoc,serverTimestamp}=state.firebase;await setDoc(doc(state.db,"participants",state.participantKey),{completedAt:serverTimestamp(),completedItems:Object.keys(state.answers).length},{merge:true})}catch(e){console.error(e)}}
function download(){const blob=new Blob([JSON.stringify({batchId:state.batchId,participantKey:state.participantKey,responses:Object.values(state.answers)},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="vmts-participant-backup.json";a.click();URL.revokeObjectURL(a.href)}

renderStudyInfo();initOptions();state.prolific=prolificParams();$("#participantStatus").textContent=state.prolific.pid&&state.prolific.studyId&&state.prolific.sessionId?"Prolific study link detected. Your task set will be assigned after consent.":"This URL is missing Prolific participant parameters. Open the study from Prolific.";
$("#beginBtn").onclick=async()=>{const error=$("#introError");error.textContent="";if(!ethicsReady())return error.textContent="This study is not open: verified ethics and study details have not been configured.";if(![$("#ageCheck"),$("#infoCheck"),$("#consentCheck")].every(x=>x.checked))return error.textContent="Please confirm all three consent statements.";const p=state.prolific;if(!p.pid||!p.studyId||!p.sessionId)return error.textContent="The Prolific participant, study, or session parameter is missing. Re-open the task from Prolific.";if(studyConfig.prolific.expectedStudyId&&p.studyId!==studyConfig.prolific.expectedStudyId)return error.textContent="This link belongs to a different Prolific study.";$("#beginBtn").disabled=true;$("#participantStatus").textContent="Assigning your task set…";try{[state.participantKey,state.studyKey,state.sessionKey]=await Promise.all([hash(`vmts|${p.studyId}|${p.pid}`),hash(p.studyId),hash(p.sessionId)]);await loadData();await connectFirebase();await assignBatch();restore();show("instructions")}catch(e){console.error(e);error.textContent=e.message||"The study could not be started. Contact the researcher.";$("#beginBtn").disabled=false}};
$("#startBtn").onclick=()=>{if(state.index>=state.items.length)return finish();show("annotate");render()};$("#annotationForm").onsubmit=async e=>{e.preventDefault();if(await saveCurrent()){state.index++;render()}};$("#backBtn").onclick=()=>{if(state.index>0){state.index--;render()}};$("#exportBtn").onclick=download;$("#clearBtn").onclick=()=>{$("#annotationForm").reset();$("#notes").value="";$("#formError").textContent=""};
