import{firebaseConfig}from"./firebase-config.js";
import{studyConfig}from"./study-config.js";

const $=s=>document.querySelector(s),screens=["intro","example","annotate","complete","declined"];
const state={participantKey:null,studyKey:null,sessionKey:null,batchId:null,batches:{},items:[],tasks:new Map(),index:0,answers:{},uid:null,db:null,firebase:null,prolific:null,preview:false};
function show(id){screens.forEach(x=>$("#"+x).classList.toggle("active",x===id));scrollTo({top:0,behavior:"smooth"})}
function configured(v){return typeof v==="string"&&v.length>0&&!v.startsWith("CONFIGURE_")}
function ethicsReady(){const e=studyConfig.ethics,p=studyConfig.prolific,s=studyConfig.study;return e.status==="APPROVED"&&[e.institution,e.reference,e.approvedDate,e.contactEmail,s.estimatedMinutes,s.payment,p.completionCode,studyConfig.consentVersion].every(configured)}
function renderStudyInfo(){const e=studyConfig.ethics,s=studyConfig.study;$("#durationText").textContent=configured(s.estimatedMinutes)?`About ${s.estimatedMinutes} minutes`:"About 15–18 minutes";$("#paymentText").textContent=configured(s.payment)?s.payment:"Shown in the Prolific listing";$("#riskText").textContent=s.risks;$("#privacyText").textContent=s.privacy;$("#withdrawalText").textContent=s.withdrawal;if(e.status==="APPROVED"&&[e.institution,e.reference,e.approvedDate,e.contactEmail].every(configured)){$("#ethicsCard").hidden=false;$("#ethicsInstitution").textContent=e.institution;$("#ethicsReference").textContent=e.reference;$("#ethicsDate").textContent=e.approvedDate;$("#ethicsContact").textContent=e.contactEmail;$("#ethicsContact").href=`mailto:${e.contactEmail}`}}
function prolificParams(){const q=new URLSearchParams(location.search),get=k=>q.get(k)||q.get(k.toLowerCase());return{pid:get("PROLIFIC_PID"),studyId:get("STUDY_ID"),sessionId:get("SESSION_ID"),preview:q.get("preview")==="1"}}
async function hash(v){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function storageKey(){return`vmts_prolific_${state.participantKey}`}
async function loadData(){const[t,b]=await Promise.all([fetch("data/tasks.json").then(r=>r.json()),fetch("data/prolific-batches.json").then(r=>r.json())]);state.tasks=new Map(t.map(x=>[x.item_id,x]));state.batches=b}
async function connectFirebase(){if(!firebaseConfig.apiKey)throw new Error("Firebase is not configured.");const[{initializeApp},{getAuth,signInAnonymously},{getFirestore,doc,setDoc,serverTimestamp,runTransaction}]=await Promise.all([import("https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js"),import("https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js"),import("https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js")]);const app=initializeApp(firebaseConfig),cred=await signInAnonymously(getAuth(app));state.uid=cred.user.uid;state.db=getFirestore(app);state.firebase={doc,setDoc,serverTimestamp,runTransaction};$("#saveState").textContent="Securely connected"}
async function assignBatch(){const{doc,runTransaction,serverTimestamp}=state.firebase,ref=doc(state.db,"participants",state.participantKey),ids=Object.keys(state.batches).sort(),offset=parseInt(state.participantKey.slice(0,8),16)%ids.length,ordered=ids.slice(offset).concat(ids.slice(0,offset));state.batchId=await runTransaction(state.db,async tx=>{const old=await tx.get(ref);if(old.exists()){const d=old.data();if(d.uid!==state.uid)throw new Error("This Prolific ID was already started in another browser profile. Contact the researcher.");return d.batchId}const claims=[];for(const id of ordered)claims.push([id,await tx.get(doc(state.db,"batchClaims",id))]);const available=claims.find(([,s])=>!s.exists());if(!available)throw new Error("All annotation places are currently assigned. Return the study on Prolific or contact the researcher.");const batchId=available[0],common={participantKey:state.participantKey,batchId,uid:state.uid,studyKey:state.studyKey,sessionKey:state.sessionKey,assignedAt:serverTimestamp()},participant={...common,consentVersion:studyConfig.consentVersion,consentedAt:serverTimestamp(),ageConfirmed:true};tx.set(doc(state.db,"batchClaims",batchId),common);tx.set(ref,participant);return batchId});if(!state.batches[state.batchId])throw new Error("Assigned batch is missing from this site version.");state.items=state.batches[state.batchId]}
function assignPreviewBatch(){const ids=Object.keys(state.batches).sort(),offset=parseInt(state.participantKey.slice(0,8),16)%ids.length;state.batchId=`PREVIEW-${ids[offset]}`;state.items=state.batches[ids[offset]]}
function restore(){try{state.answers=JSON.parse(localStorage.getItem(storageKey())||"{}")}catch{state.answers={}}const first=state.items.findIndex(id=>!state.answers[id]?.submitted);state.index=first<0?state.items.length:first}
function options(name,noLabel,noneLabel){return[["current","Yes"],["legacy",noLabel],["mixed","It mixes both rules"],["unclear","Cannot tell"],[name==="action_consistency_label"?"abstention":"empty",noneLabel]].map(([v,l])=>`<label><input type="radio" name="${name}" value="${v}"> ${l}</label>`).join("")}
function render(){if(state.index>=state.items.length)return finish();const id=state.items[state.index],t=state.tasks.get(id),a=state.answers[id]||{};$("#counter").textContent=`Question ${state.index+1} of ${state.items.length}`;$("#progressBar").style.width=`${100*(state.index+1)/state.items.length}%`;$("#topic").textContent=t.topic;$("#before").textContent=t.before;$("#now").textContent=t.now;$("#candidateAction").textContent=t.action;$("#candidateWrite").textContent=t.saved_note;$("#actionOptions").innerHTML=options("action_consistency_label","No — it follows the old rule","No action was taken");$("#writeOptions").innerHTML=options("write_consistency_label","No — it follows the old rule","No note was saved");Object.entries(a).forEach(([k,v])=>document.querySelector(`[name="${k}"][value="${CSS.escape(String(v))}"]`)?.click());$("#formError").textContent=""}
function collect(){const fd=new FormData($("#annotationForm"));return{action_consistency_label:fd.get("action_consistency_label"),write_consistency_label:fd.get("write_consistency_label")}}
async function saveCurrent(){const itemId=state.items[state.index],answer=collect();if(!answer.action_consistency_label||!answer.write_consistency_label){$("#formError").textContent="Please answer both questions.";return false}const payload={revision_relation_label:"unclear",...answer,mixed_validity_preservation_label:"unclear",confidence_1_to_5:"3",notes:"",itemId,batchId:state.batchId,participantKey:state.participantKey,studyKey:state.studyKey,sessionKey:state.sessionKey,uid:state.uid,submitted:true,clientUpdatedAt:new Date().toISOString()};state.answers[itemId]=payload;localStorage.setItem(storageKey(),JSON.stringify(state.answers));if(state.preview){$("#saveState").textContent="Preview only — saved in this browser";return true}try{const{doc,setDoc,serverTimestamp}=state.firebase;await setDoc(doc(state.db,"responses",`${state.participantKey}_${itemId}`),{...payload,serverUpdatedAt:serverTimestamp()},{merge:true});$("#saveState").textContent="Saved securely"}catch(e){console.error(e);$("#formError").textContent="Could not save. Check your connection and try again.";return false}return true}
async function finish(){show("complete");if(state.preview){$("#completionCode").textContent="PREVIEW ONLY";$("#completeText").textContent=`Preview complete. ${state.items.length} responses stayed in this browser.`;$("#prolificReturnBtn").hidden=true;return}$("#completionCode").textContent=studyConfig.prolific.completionCode;$("#prolificReturnBtn").href=studyConfig.prolific.completionUrl;try{const{doc,setDoc,serverTimestamp}=state.firebase;await setDoc(doc(state.db,"participants",state.participantKey),{completedAt:serverTimestamp(),completedItems:Object.keys(state.answers).length},{merge:true})}catch(e){console.error(e)}}

renderStudyInfo();state.prolific=prolificParams();state.preview=state.prolific.preview;$("#participantStatus").textContent=state.preview?"Preview mode — no data will be submitted.":state.prolific.pid&&state.prolific.studyId&&state.prolific.sessionId?"Prolific study link detected.":"Open this study from Prolific.";if(state.preview)$("#saveState").textContent="PREVIEW — no data submission";
function consentReady(){$("#beginBtn").disabled=!($("#ageConsent").checked&&$("#voluntaryConsent").checked)}
$("#ageConsent").onchange=consentReady;$("#voluntaryConsent").onchange=consentReady;
$("#beginBtn").onclick=async()=>{const error=$("#introError"),p=state.prolific;error.textContent="";$("#beginBtn").disabled=true;try{if(state.preview){const id=p.pid||"LOCAL-PREVIEW";[state.participantKey,state.studyKey,state.sessionKey]=await Promise.all([hash(`preview|${id}`),hash("preview-study"),hash("preview-session")]);await loadData();assignPreviewBatch()}else{if(!ethicsReady())throw new Error("This study is not yet open. Please return it on Prolific or contact the researcher.");if(!p.pid||!p.studyId||!p.sessionId)throw new Error("The Prolific participant, study, or session parameter is missing.");if(studyConfig.prolific.expectedStudyId&&p.studyId!==studyConfig.prolific.expectedStudyId)throw new Error("This link belongs to a different Prolific study.");[state.participantKey,state.studyKey,state.sessionKey]=await Promise.all([hash(`vmts|${p.studyId}|${p.pid}`),hash(p.studyId),hash(p.sessionId)]);await loadData();await connectFirebase();await assignBatch()}restore();show("example")}catch(e){console.error(e);error.textContent=e.message||"The study could not be started.";$("#beginBtn").disabled=false}};
$("#declineBtn").onclick=()=>{state.answers={};show("declined");if(!state.preview){const url=studyConfig.prolific.declineUrl||"https://app.prolific.com/";$("#declineReturnBtn").href=url;setTimeout(()=>location.assign(url),1500)}};
$("#checkExample").onclick=()=>{const v=document.querySelector('[name="example"]:checked')?.value;if(!v)return $("#exampleFeedback").textContent="Choose one answer first.";if(v==="legacy"){$("#exampleFeedback").textContent="Correct. 5:30 p.m. follows the old rule, not the current 5 p.m. limit.";$("#startBtn").hidden=false;$("#checkExample").hidden=true}else $("#exampleFeedback").textContent="Not quite. The current rule ends entry at 5 p.m."};
$("#startBtn").onclick=()=>{if(state.index>=state.items.length)return finish();show("annotate");render()};$("#annotationForm").onsubmit=async e=>{e.preventDefault();if(await saveCurrent()){state.index++;render()}};$("#backBtn").onclick=()=>{if(state.index>0){state.index--;render()}};
